package serviceInterface.autosar.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Client = 0;
  public static final int ClientRef = 1;
  public static final int DataElement = 2;
  public static final int DataElementType = 3;
  public static final int Event = 4;
  public static final int Function = 5;
  public static final int MethodArgRef = 6;
  public static final int MethodCall = 7;
  public static final int MethodReturnRef = 8;
  public static final int PeriodicNotificationEvent = 9;
  public static final int Service = 10;
  public static final int ServiceInterface = 11;
  public static final int ServiceInterfaceType = 12;
  public static final int ServiceRef = 13;
  public static final int SporadicEvent = 14;
  public static final int Struct = 15;
  public static final int Type = 16;
  public static final int ufloat32_t = 17;
  public static final int uint32_t = 18;
  public static final int uint8_t = 19;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x5edcd1c61ac4826L, 0xb1da37adef86448dL);
    builder.put(0x36d24cda9c1fe380L, Client);
    builder.put(0x36d24cda9c203d36L, ClientRef);
    builder.put(0x36d24cda9c1fed4eL, DataElement);
    builder.put(0x3203e1423891c347L, DataElementType);
    builder.put(0x36d24cda9c1feba4L, Event);
    builder.put(0x36d24cda9c1fd8aeL, Function);
    builder.put(0x36d24cda9c267312L, MethodArgRef);
    builder.put(0x36d24cda9c1fee3aL, MethodCall);
    builder.put(0x36d24cda9c2678afL, MethodReturnRef);
    builder.put(0x36d24cda9c1feda0L, PeriodicNotificationEvent);
    builder.put(0x36d24cda9c1fe340L, Service);
    builder.put(0x36d24cda9c1fe3c0L, ServiceInterface);
    builder.put(0x3203e1423891422cL, ServiceInterfaceType);
    builder.put(0x36d24cda9c203b9eL, ServiceRef);
    builder.put(0x36d24cda9c1fec99L, SporadicEvent);
    builder.put(0x36d24cda9c1ff39bL, Struct);
    builder.put(0x36d24cda9c1ff325L, Type);
    builder.put(0x36d24cda9c1ff929L, ufloat32_t);
    builder.put(0x36d24cda9c1ff639L, uint32_t);
    builder.put(0x36d24cda9c1ff4bdL, uint8_t);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
