package serviceInterface.autosar.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.menus.substitute.SubstituteMenuBase;
import jetbrains.mps.lang.editor.menus.EditorMenuDescriptorBase;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.annotations.NotNull;
import java.util.List;
import jetbrains.mps.lang.editor.menus.MenuPart;
import jetbrains.mps.openapi.editor.menus.substitute.SubstituteMenuItem;
import jetbrains.mps.openapi.editor.menus.substitute.SubstituteMenuContext;
import java.util.ArrayList;
import jetbrains.mps.lang.editor.menus.substitute.ConstraintsFilteringSubstituteMenuPartDecorator;
import jetbrains.mps.lang.editor.menus.substitute.ReferenceScopeSubstituteMenuPart;
import jetbrains.mps.lang.editor.menus.ConceptMenusPart;
import java.util.Collection;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.editor.menus.substitute.DefaultSubstituteMenuLookup;
import jetbrains.mps.smodel.language.LanguageRegistry;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SReferenceLink;

public class MethodArgRef_SubstituteMenu extends SubstituteMenuBase {
  public MethodArgRef_SubstituteMenu() {
    super(false, new EditorMenuDescriptorBase("default substitute menu for MethodArgRef. Generated from implicit smart reference attribute.", new SNodePointer("r:317e77fa-abb5-4e94-a26f-3685ead9e495(serviceInterface.autosar.structure)", "3950304324963693330")));
  }
  @NotNull
  @Override
  protected List<MenuPart<SubstituteMenuItem, SubstituteMenuContext>> getParts(final SubstituteMenuContext _context) {
    List<MenuPart<SubstituteMenuItem, SubstituteMenuContext>> result = new ArrayList<MenuPart<SubstituteMenuItem, SubstituteMenuContext>>();
    result.add(new ConstraintsFilteringSubstituteMenuPartDecorator(new SMP_ReferenceScope_o9l5yl_a(), CONCEPTS.MethodArgRef$qi));
    result.add(new SMP_Subconcepts_o9l5yl_b());
    return result;
  }

  public class SMP_ReferenceScope_o9l5yl_a extends ReferenceScopeSubstituteMenuPart {

    public SMP_ReferenceScope_o9l5yl_a() {
      super(CONCEPTS.MethodArgRef$qi, LINKS.arguementtarget$BId7, new EditorMenuDescriptorBase("reference scope substitute menu part", null));
    }

  }
  public class SMP_Subconcepts_o9l5yl_b extends ConceptMenusPart<SubstituteMenuItem, SubstituteMenuContext> {
    public SMP_Subconcepts_o9l5yl_b() {
      super(new EditorMenuDescriptorBase("include menus for all the direct subconcepts of " + "MethodArgRef", null));
    }

    @Override
    protected Collection<SAbstractConcept> getConcepts(final SubstituteMenuContext _context) {
      return getDirectDescendants(_context, CONCEPTS.MethodArgRef$qi);
    }

    @Override
    protected Collection<SubstituteMenuItem> createItemsForConcept(SubstituteMenuContext context, SAbstractConcept concept) {
      return context.createItems(new DefaultSubstituteMenuLookup(LanguageRegistry.getInstance(context.getEditorContext().getRepository()), concept));
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept MethodArgRef$qi = MetaAdapterFactory.getConcept(0x5edcd1c61ac4826L, 0xb1da37adef86448dL, 0x36d24cda9c267312L, "serviceInterface.autosar.structure.MethodArgRef");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink arguementtarget$BId7 = MetaAdapterFactory.getReferenceLink(0x5edcd1c61ac4826L, 0xb1da37adef86448dL, 0x36d24cda9c267312L, 0x36d24cda9c2673acL, "arguementtarget");
  }
}
